//fix routes
export enum ROUTES {
  LOGIN = "/login",
  REGISTER = "/register",
  DASHBOARD = "/",
  SETTINGS = "/settings",
  HELPANDFEEDBACK = "/help-and-feedback",
  RESOURCEBYID = "/resources/:id",
  NEWRESOURCE = "/new-resource",
  HIRENOW = "hire-now",
  HIRENOWRESOURCE = "/hire-now/new-resource",
  RESOURCES = "/resources",
  HIRED_RESOURCES = "/resources#hire",
  FAVORITE_RESOURCES = "/resources#favorite",
  HIRENOWREPLACE = "/hire-now",
  CREATE_RESOURCE = "/create-resource",
  CREATE_PROJECT = "/project/create-project",
  UPDATE_PROJECT = "/project/:id/update-project",
  PROJECT = "/project",
  PROFILERESOURCEBYID = "/hire-now/resources/:id",
  SCHEDULE_INTERVIEW = "/hire-now/resources/:id/schedule-interview",
  INTERVIEW = "/interviews",
  INQUIRIES = "/inquiries",
  INVOICES = "/invoices",
  INVOICEBYID = "/invoices/:id",
  TIMESHEETBYID = ":id", // temp bases
  TIMESHEETS = "timesheets",
  UPDATE_INTERVIEW = "/interviews/:id/schedule-interview",
  HIRE_RESOURCE = "/hire-now/resources/:id/hire-resource",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  ENGAGEMENTS = "/resources/:id/engagements",
  VIEW_TIMESHEET = "/resources/:id/engagements/:engId/timesheets",
  VIEW_TIMESHEET_ENGAGEMENT = "/engagements/:engId/timesheets",
  VIEW_INVOICE_TIMESHEET = "/engagements/:engId/timesheets/:id",
  CHATBOT = "/chatbot",
  // more routes will be added here
}
